name: helmy_project
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+6

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  url_launcher: any

  share_plus:

  font_awesome_flutter:

  loading_indicator:

  whatsapp_unilink:

  google_sign_in: ^6.2.1

  sign_in_with_apple: ^6.1.1

  # Helps monitor network connectivity
  connectivity_plus:

  # Provides state management using BLoC architecture
  flutter_bloc:

  # Provides metadata annotations for code generation
  meta:

  # Allows text to automatically size itself to fit within its bounds
  auto_size_text:

  # Adds shimmering effect to Flutter widgets for loading UIs
  shimmer:

  # Dependency injection container for managing application dependencies
  get_it:

  # Provides utilities for creating equatable objects for comparison
  equatable:

  # Checks for internet connectivity status
  internet_connection_checker:

  # Logs HTTP requests and responses in a readable format
  pretty_dio_logger:

  # Provides a simple way to store and retrieve key-value pairs (persistent storage)
  shared_preferences:

  # Adds internationalization and localization support to your app
  easy_localization:

  # Provides utilities for working with screen sizes and fonts
  flutter_screenutil:

  # State management library using the Provider pattern
  provider:

  # Creates a dotted border around widgets for styling
  dotted_border:

  # Allows you to add badges to widgets for notification indicators
  badges:

  # Renders SVG images in Flutter for vector graphics
  flutter_svg:

  # Provides a searchable dropdown widget for user selection
  dropdown_search:

  # Creates a rating bar widget for user ratings and feedback
  flutter_rating_bar:

  # Implements a pin code input field for user authentication
  pin_code_fields:

  # Hydrated automatically persists and restores bloc and cubit states.
  # hydrated_bloc: ^9.1.2

  # Get the application documents directory for file operations
  path_provider:

  # HTTP requests and REST API communication
  dio:

  # Either Package for functional error handling
  either_dart:

  dartz:
  
  # Dropdown package for customizable selection menus
  dropdown_button2:

  # Get package for dependency injection
  get:

  # Lottie for rendering animations in Flutter
  lottie:
  iconly:

  # Flutter Ringtone Player for playing ringtones
  # flutter_ringtone_player:

  # Vibration for haptic feedback and vibration control
  # vibration:

  flutter_local_notifications:
  firebase_messaging:

  firebase_core:
  firebase_analytics:

  flutter_widget_from_html:

  hive:
  hive_flutter:
  #  pusher_channels_flutter: ^2.2.0
  rename: ^3.0.1


  mime_type:
  image_picker:
  flutter_image_compress:

  webview_flutter:
  webview_flutter_web:

  webview_flutter_wkwebview:

  country_flags:
  country_code_picker:

  audioplayers: 
  # flutter_voice_recorder:
  record:

  flutter_paytabs_bridge:

  record_mp3:
  
  permission_handler:

  flutter_exif_rotation:
  flutter_appauth: ^6.0.6
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  supabase_flutter: ^2.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints:
  json_serializable: ^6.7.1
  build_runner:



  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconHelmyLogo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300

    - family: Tqneen
      fonts:
        - asset: assets/fonts/Tqneen.ttf

  assets:
    - assets/images/
    - assets/translations/
    - assets/lotties/


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
